name: CodiumAI PR Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  ai_pr_review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run CodiumAI PR Agent
        uses: Codium-ai/PR-Agent@main
        env:
          GITHUB_API_TOKEN: ${{ secrets.PR_BUDDY_API_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}